"""Initial migration

Revision ID: 1233c5cc471a
Revises: 
Create Date: 2025-12-13 11:08:06.259533+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1233c5cc471a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifiant unique auto-incrémenté'),
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Identifiant UUID unique pour sécurité API'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="Adresse email de l'utilisateur (unique, utilisée pour connexion)"),
    sa.Column('username', sa.String(length=20), nullable=False, comment="Pseudo de l'utilisateur (unique, utilisé pour connexion)"),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Mot de passe haché avec bcrypt'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment="Prénom de l'utilisateur"),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment="Nom de famille de l'utilisateur"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indique si le compte utilisateur est actif'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment="Indique si l'utilisateur a les droits administrateur"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment="Date de dernière modification de l'enregistrement"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_fullname', 'users', ['first_name', 'last_name'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_uuid', 'users', ['uuid'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_uuid', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_fullname', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
